remote_theme: thakyZ/minima
title: Nick Mullally
description: Portfolio
show_downloads: false

minima:
  skin: material

minima:
  date_format: "%b %-d, %Y"

header_pages:
  - index.md
  - portfolio.md

author:
  name: Nick Mullally
  email: "nekoboinick@gmail.com"

plugins:
  - jekyll-remote-theme
