remote_theme: thakyZ/minima
title: ***REMOVED***
description: Portfolio
show_downloads: false

minima:
  skin: material

minima:
  date_format: "%b %-d, %Y"

header_pages:
  - about.md
  - gallery.md
  - portfolio.md

author:
  name: ***REMOVED***
  email: "nekoboinick@gmail.com"

plugins:
  - jekyll-remote-theme
