remote_theme: jekyll/minima
title: Neko Boi Nick
description: Portfolio
show_downloads: false

minima:
  skin: material

minima:
  date_format: "%b %-d, %Y"

header_pages:
  - index.md
  - portfolio.md

plugins:
  - jekyll-remote-theme
